plugins:
  - "@typescript-eslint"
parserOptions:
  parser: "@typescript-eslint/parser"
rules:
  vue/html-self-closing: "off"
  vue/html-indent: "off"
  no-unused-vars: "off"  # TODO: https://github.com/typescript-eslint/typescript-eslint/issues/363
extends:
  - "@nuxtjs"
  - "plugin:prettier/recommended"
